### ISSUE TITLE
how to return an autoincrementing numeric value, celll content

### ISSUE THREAD

**Issue by CRIS19N** [pjjonesnz/datatables-buttons-excel-styles#10]
{
              cells: ["sAh", "sAf"], 
              content: "N. rows", 
              pushCol: true, 
            },
            {
              cells: "sA1:A-0",
              content: "", // here i need to add my function which returns i++ 0:n
              pushCol: true, 
            },

**Comment by pjjonesnz** [comment]
Sorry, it's been a while since I've done all of this, but you can use a function to return content.  Have at look at the following example: https://www.pauljones.co.nz/github/buttons-html5-styles/examples/page_style.html

```
function dynamicContentFunction(cellId, col, row, smartRow) { 
    return 'Cell: ' + cellId + ' Col: ' + col + ' Row: ' + row + ' Smart Row: ' + smartRow;
};

...{
      cells: ['sC1:D14','sC18:D-0'],
      content: dynamicContentFunction,    // Content inserted by a function
      pushCol: true
  },
```
