### ISSUE TITLE
Supports DataTables Grouping?

### ISSUE THREAD

**Issue by nikitul** [pjjonesnz/datatables-buttons-excel-styles#3]
I love your plugin. It's waaaaw!

I have some questions though:

1. These templates supports DataTable row Grouping?
Is there an example with row grouping? 

2. Is there an easy way to use current templates on a table with complex headers (two or tree rows for header)?

3. Is there an easy way to synchronize table colors (custom class)  with excel styles or templates (what you see on table is what you get in excel)?

Thank you for your time.

**Comment by pjjonesnz** [comment]
Hi @nikitul 

So pleased that you love the plugin! :)

1. Unfortunately the DataTable row Grouping extension isn't supported by the Buttons HTML5 Excel export function: [see compatibility](https://datatables.net/download/compatibility). 
2. Again, unfortunately the Buttons HTML5 Excel export doesn't export the extra rows.  The only way to do this would be to insert your own content, and then apply the templates manually.  I've [created an example](https://www.pauljones.co.nz/github/buttons-html5-styles/examples/complex_headers.html) for you.
3. Unfortunately no

Sorry, I haven't been a lot of help with this.  There are limitations with the HTML Buttons extension not exporting parts of the table.  My plugin only applies styling to the content exported by [Buttons](https://datatables.net/extensions/buttons/)

**Comment by nikitul** [comment]
Hi @pjjonesnz,
...very busy year...

Thank you very much for your answer and for your example.

Best Regards
