### ISSUE TITLE
Insertar una fila despues del encabezado??

### ISSUE THREAD

**Issue by davidfaguas** [pjjonesnz/datatables-buttons-excel-styles#6]
Hola estimado consulta como es posible, insertar una fila después del encabezado para tratar de emular un rowspan::

https://plnkr.co/edit/CKvdqybxYv5BxiCg?open=lib%2Fscript.js

Existira la posibilidad de dejarlo como este ejemplo:: la parte del encabezado:

[ReporteSubDimensionesAplicados (36).xls](https://github.com/pjjonesnz/datatables-buttons-excel-styles/files/6650778/ReporteSubDimensionesAplicados.36.xls)

**Comment by pjjonesnz** [comment]
I've added mergeCells support to help you do what you are after.

Here is an example of what you can do now: [https://plnkr.co/edit/Z29qnWvx1wIPd24L](https://plnkr.co/edit/Z29qnWvx1wIPd24L)

You make a list of cells that you want to be merged in a pageStyle block list this: 

```pageStyle: {
    mergeCells: {
	    mergeCell: [ 
		    'I2:K3',
		    'L2:N3',
		    'P2:X2',
		    'Y2:AC2',
		    'P3:R3',
		    'S3:U3',
	    ]
    }
  }
```

I hope this helps.  Note that you need version 1.1.4 of the plugin for mergeCells to work.

**Comment by davidfaguas** [comment]
Te pasaste Paul muchas gracias amigo es justo lo que necesitaba.

**Comment by pjjonesnz** [comment]
You are very welcome.  Sorry that there isn't an automatic way to export your headers.  I see that [other people have asked for this](https://datatables.net/forums/discussion/51682/complex-headers-export-to-excel).

All the best, Paul

**Comment by davidfaguas** [comment]
Pero Paul con lo que me acabas de ayudar, justo es lo que necesitaba, en un futuro habrá que automatizar este trabajo pero por el momento esta muy bien se agradece mucho el tiempo y dedicación a tus respuestas, que Dios te bendiga mucho.

**Comment by pjjonesnz** [comment]
Thank you @davidfaguas 

God bless you too
