### ISSUE TITLE
Apply style to the entire row on conditions

### ISSUE THREAD

**Issue by MrR0b0t14** [pjjonesnz/datatables-buttons-excel-styles#7]
Hi Paul, 
First thank you for your work, this is amazing. Secondly, I was wondering how to apply style to an entire row throughout the conditions. What I mean is that when I make a condition on a cell, I am able to apply some style just to that cell which matches the condition, I'd like to, for instance, change the background color of the entire row in which there is a cell that matches condition.
Thank you!

**Comment by pjjonesnz** [comment]
Hi @MrR0b0t14 

You're very welcome - nice to hear that it is useful.

That is no trouble to do that. You select a range of cells that you want to apply the formatting to, and then you have to use a formula to match the cell that has the data that you wish to run the condition on, but you use a $ sign before the cell reference to 'lock on' to that cell.

So, here is an example.

```json
{
    "excelStyles": [
        {
            "cells": "s:",
            "condition": {
                "type": "expression",
                "formula": "AND($F3>150000,$F3<250000)"
            },
            "style": {
                "font": {
                    "b": true
                },
                "fill": {
                    "pattern": {
                        "bgColor": "FFCCCC"
                    }
                }
            }
        }
    ]
}
```

### Explanation:

`"cells": "s:"`  - Use smart cell references to target all data cells in the table
`"type": "expression"` - Use an expression for the condition
`"formula": "AND($F3>150000,$F3<250000)"` - The formula - notice the $ before the F - also note that you can't use smart row references in here.  This assumes that the first data row is row 3 (ie. row 1 is the table title, row 2 the header and row 3 the first of the data rows), and that column F has the data that you wish to match the condition against.

I have added this example to the [live example page here](https://www.pauljones.co.nz/github/buttons-html5-styles/examples/simple_table_style.html)

### Note:

Note for the formula, DON'T precede it with a = like you normally would in Excel.

For a single condition you can use something like: `$F3>150000` - I used the AND example above to show that you just use standard excel functions in the formula.

Or, highlight cell B to F for all Software Engineers earning more than $150000:

```json
{
    "excelStyles": [
        {
            "cells": "sB:F",    
            "condition": {
                "type": "expression",     
                "formula": "AND($F3>150000,$B3=\"Software Engineer\")"            },
            "style": { 
                "font": {
                    "b": true
                },
                "fill": {
                    "pattern": {
                        "bgColor": "FFCCCC"
                    }
                }
            }
        }
    ]
}
```

note the \ before the speechmarks around the text you wish to match.

Hope that helps.

**Comment by pjjonesnz** [comment]
I've just added that example to the [live demo page](https://www.pauljones.co.nz/github/buttons-html5-styles/examples/simple_table_style.html)

Called 'Add Styles Conditionally - using a formula'
