### ISSUE TITLE
Freeze header row

### ISSUE THREAD

**Issue by chaleyct** [pjjonesnz/datatables-buttons-excel-styles#9]
Hello @pjjonesnz!

This is an amazing library, but one feature I could not figure out how to implement are frozen header panes. This would typically be solved "manually" by writing the following:
```Javascript
customize: function( xlsx ) {
                var sheet = xlsx.xl.worksheets['sheet1.xml'];
                var f1 = `<sheetViews>
                        <sheetView tabSelected="1" workbookViewId="0">
                               <pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen" />
                        </sheetView>
                   </sheetViews>`;
                $('worksheet', sheet).prepend(f1);
```
Are there plans to add this or perhaps I might have overlooked something in the documentation? Thank you for your time.

**Comment by pjjonesnz** [comment]
Thanks so much for your comment.  You're correct that this isn't implemented, but I'll make a note of it for next time I make some changes.
